/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FateProfileRouteImport } from './routes/fate-profile'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ResultPredictionIdRouteImport } from './routes/result.$predictionId'
import { Route as VerifyPredictionIdRouteImport } from './routes/verify.$predictionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FateProfileRoute = FateProfileRouteImport.update({
  id: '/fate-profile',
  path: '/fate-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultPredictionIdRoute = ResultPredictionIdRouteImport.update({
  id: '/result/$predictionId',
  path: '/result/$predictionId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPredictionIdRoute = VerifyPredictionIdRouteImport.update({
  id: '/verify/$predictionId',
  path: '/verify/$predictionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chronicle': typeof ChronicleRoute
  '/docs': typeof DocsRoute
  '/fate-profile': typeof FateProfileRoute
  '/features': typeof FeaturesRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/result/$predictionId': typeof ResultPredictionIdRoute
  '/verify/$predictionId': typeof VerifyPredictionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chronicle': typeof ChronicleRoute
  '/docs': typeof DocsRoute
  '/fate-profile': typeof FateProfileRoute
  '/features': typeof FeaturesRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/result/$predictionId': typeof ResultPredictionIdRoute
  '/verify/$predictionId': typeof VerifyPredictionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chronicle': typeof ChronicleRoute
  '/docs': typeof DocsRoute
  '/fate-profile': typeof FateProfileRoute
  '/features': typeof FeaturesRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/result/$predictionId': typeof ResultPredictionIdRoute
  '/verify/$predictionId': typeof VerifyPredictionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chronicle'
    | '/docs'
    | '/fate-profile'
    | '/features'
    | '/history'
    | '/how-it-works'
    | '/leaderboard'
    | '/result/$predictionId'
    | '/verify/$predictionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chronicle'
    | '/docs'
    | '/fate-profile'
    | '/features'
    | '/history'
    | '/how-it-works'
    | '/leaderboard'
    | '/result/$predictionId'
    | '/verify/$predictionId'
  id:
    | '__root__'
    | '/'
    | '/chronicle'
    | '/docs'
    | '/fate-profile'
    | '/features'
    | '/history'
    | '/how-it-works'
    | '/leaderboard'
    | '/result/$predictionId'
    | '/verify/$predictionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChronicleRoute: typeof ChronicleRoute
  DocsRoute: typeof DocsRoute
  FateProfileRoute: typeof FateProfileRoute
  FeaturesRoute: typeof FeaturesRoute
  HistoryRoute: typeof HistoryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ResultPredictionIdRoute: typeof ResultPredictionIdRoute
  VerifyPredictionIdRoute: typeof VerifyPredictionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fate-profile': {
      id: '/fate-profile'
      path: '/fate-profile'
      fullPath: '/fate-profile'
      preLoaderRoute: typeof FateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$predictionId': {
      id: '/result/$predictionId'
      path: '/result/$predictionId'
      fullPath: '/result/$predictionId'
      preLoaderRoute: typeof ResultPredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$predictionId': {
      id: '/verify/$predictionId'
      path: '/verify/$predictionId'
      fullPath: '/verify/$predictionId'
      preLoaderRoute: typeof VerifyPredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChronicleRoute: ChronicleRoute,
  DocsRoute: DocsRoute,
  FateProfileRoute: FateProfileRoute,
  FeaturesRoute: FeaturesRoute,
  HistoryRoute: HistoryRoute,
  HowItWorksRoute: HowItWorksRoute,
  LeaderboardRoute: LeaderboardRoute,
  ResultPredictionIdRoute: ResultPredictionIdRoute,
  VerifyPredictionIdRoute: VerifyPredictionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
